package admin;

/**
 * All possible permissions in this program.
 */
public enum Permission
{
    ACCESS_COURSE_NAME,
    ACCESS_COURSE_SNAPSHOT,
    ACCESS_COURSE_GRADE_SCHEMA,
    ACCESS_COURSE_LATE_POLICY,
    CREATE_COURSE_SNAPSHOT,
    UPDATE_COURSE_NAME,
    UPDATE_COURSE_GRADE_SCHEMA,
    UPDATE_COURSE_LATE_POLICY
}
